name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  spm-build-test:
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Remove AppAuth.xcodeproj
      run: rm -rf AppAuth.xcodeproj
    - name: Build unit test targets
      run: |
        xcodebuild build-for-testing \
          -scheme AppAuth-Package \
          -sdk 'iphonesimulator' \
          -destination 'platform=iOS Simulator,name=iPhone 11' \
    - name: Run unit test targets
      run: |
        xcodebuild test-without-building \
          -scheme AppAuth-Package \
          -sdk 'iphonesimulator' \
          -destination 'platform=iOS Simulator,name=iPhone 11' \
          -enableCodeCoverage YES
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
